name: Create Issue Workflow

on:
  workflow_call: # Permite que outros repositórios chamem este workflow
    inputs:
      title:
        required: true
        type: string
      body:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create an Issue
        uses: peter-evans/create-issue@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ inputs.title }}
          body: ${{ inputs.body }}
